### ISSUE TITLE
Command line option

### ISSUE THREAD

**Issue by Chris2011** [fengyuanchen/postcss-header#4]
Hi, I use PostCSS as a command line called from a Java application. CSSNano is used via the config. I just do input.js to output.js. I need to add extra content to the output.js file. Sure I can do it manually but I would prefer to use your plugin. So long story short, is it possible to have a command line argument to add content to the cli that it will be added to the output.js file? That would be nice.

**Comment by fengyuanchen** [comment]
Try this:

```sh
postcss --use postcss-header -o output.js input.js
```

**Comment by Chris2011** [comment]
Thx will try this.
